import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import WhatsAppButton from "./ui/WhatsAppButton";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://geminiengineeringworks.in/"),
  title: {
    default:
      "Buy PSC & RCC Poles in Tamil Nadu | Gemini Engineering Works, Pudukkottai",
    template: "%s | Gemini Engineering Works",
  },
  description:
    "Buy PSC poles and RCC poles in Tamil Nadu from Gemini Engineering Works, Pudukkottai. Leading manufacturer since 1999. Order RCC poles (9m, 150kg), PSC poles (8m-9m, 200-300kg) in Tamilnadu. TNEB approved supplier. Bulk orders welcome. Call +91 63744 48522.",
  keywords: [
    // PURCHASE - Primary target keywords (placed first for relevance)
    "purchase psc pole tamilnadu",
    "purchase psc pole tamil nadu",
    "purchase psc pole TamilNadu",
    "purchase psc poles tamilnadu",
    "purchase psc poles tamil nadu",
    "purchase rcc pole tamilnadu",
    "purchase rcc pole tamil nadu",
    "purchase rcc poles tamilnadu",
    "purchase electric pole tamilnadu",
    "purchase electric pole tamil nadu",
    "purchase concrete pole tamilnadu",
    // PSC pole - buy variations with ALL location spellings
    "buy psc pole",
    "buy psc poles",
    "buy psc pole tamil nadu",
    "buy psc pole tamilnadu",
    "buy psc pole TamilNadu",
    "buy psc pole Tamilnadu",
    "buy psc poles tamil nadu",
    "buy psc poles tamilnadu",
    "buy psc poles TamilNadu",
    "buy psc poles online",
    "buy psc poles in tamil nadu",
    "buy psc poles in tamilnadu",
    "psc pole suppliers tamil nadu",
    "psc pole suppliers tamilnadu",
    "psc poles tamilnadu",
    "psc poles TamilNadu",
    "psc pole price tamil nadu",
    "psc pole price tamilnadu",
    // RCC pole - buy variations with ALL location spellings
    "buy rcc pole",
    "buy rcc poles",
    "buy rcc pole tamil nadu",
    "buy rcc pole tamilnadu",
    "buy rcc pole TamilNadu",
    "buy rcc pole Tamilnadu",
    "buy rcc poles tamil nadu",
    "buy rcc poles tamilnadu",
    "buy rcc poles TamilNadu",
    "buy rcc poles online",
    "buy rcc poles in tamil nadu",
    "buy rcc poles in tamilnadu",
    "rcc pole suppliers tamil nadu",
    "rcc pole suppliers tamilnadu",
    "rcc poles tamilnadu",
    "rcc poles TamilNadu",
    "rcc pole price tamil nadu",
    "rcc pole price tamilnadu",
    // Electric pole variations
    "buy electric pole",
    "buy electric poles tamil nadu",
    "buy electric pole tamilnadu",
    "buy electric pole TamilNadu",
    "electric pole manufacturers tamil nadu",
    "electric pole manufacturers tamilnadu",
    "electric pole manufacturers TamilNadu",
    "electric poles tamilnadu",
    "electric poles TamilNadu",
    // Concrete pole variations
    "buy concrete pole tamil nadu",
    "buy concrete poles tamilnadu",
    "concrete pole manufacturers tamil nadu",
    "concrete pole suppliers tamilnadu",
    "concrete poles TamilNadu",
    // Order variations
    "order psc pole tamilnadu",
    "order psc pole tamil nadu",
    "order rcc pole tamilnadu",
    "order rcc pole tamil nadu",
    "order electric pole tamilnadu",
    "where to buy psc pole tamilnadu",
    "where to buy rcc pole tamil nadu",
    "where to buy electric pole tamilnadu",
    // For sale variations
    "rcc pole for sale",
    "psc pole for sale",
    "electric pole for sale",
    "rcc poles for sale tamil nadu",
    "rcc poles for sale tamilnadu",
    "psc poles for sale tamil nadu",
    "psc poles for sale tamilnadu",
    // Manufacturers and suppliers - ALL spellings
    "PSC pole manufacturers",
    "RCC pole manufacturers",
    "PSC pole manufacturers tamil nadu",
    "PSC pole manufacturers tamilnadu",
    "PSC pole manufacturers TamilNadu",
    "RCC pole manufacturers tamil nadu",
    "RCC pole manufacturers tamilnadu",
    "RCC pole manufacturers TamilNadu",
    "TNEB pole suppliers",
    "TNEB pole suppliers tamil nadu",
    "TNEB pole suppliers tamilnadu",
    "Pudukkottai pole manufacturers",
    "Tamil Nadu pole manufacturers",
    "TamilNadu pole manufacturers",
    "Tamilnadu pole manufacturers",
    "electricity pole suppliers tamilnadu",
    "infrastructure pole manufacturers",
    // Price related keywords
    "psc pole price",
    "rcc pole price",
    "electric pole price tamil nadu",
    "psc pole rate tamilnadu",
    "rcc pole rate tamil nadu",
    // Product specific
    "RCC base plate manufacturers",
    "RCC base plate tamil nadu",
    "9m RCC poles",
    "9m RCC poles tamilnadu",
    "8m PSC poles",
    "8m PSC poles tamil nadu",
    "9m PSC poles",
    "9m PSC poles tamilnadu",
    "Gemini Engineering Works",
    "pole manufacturing company tamil nadu",
    "electric pole casting yard tamilnadu",
    // Best/Top variations
    "best psc pole manufacturers tamil nadu",
    "best rcc pole suppliers tamilnadu",
    "top electric pole manufacturers TamilNadu",
    // PSCC and PCC terminology (alternate industry terms)
    "PSCC poles",
    "PSCC pole manufacturers",
    "PSCC poles tamil nadu",
    "PSCC poles tamilnadu",
    "buy PSCC poles",
    "PSCC pole suppliers",
    "PCC poles",
    "PCC pole manufacturers tamil nadu",
    "pre-stressed concrete poles",
    "pre stressed concrete poles tamil nadu",
    "prestressed concrete poles",
    "reinforced cement concrete poles",
    "reinforced concrete poles tamil nadu",
    "concrete electric poles",
    "electric utility poles",
    // District-specific keywords (Geographic targeting)
    "PSC pole Chennai",
    "RCC pole Chennai",
    "electric pole manufacturer Chennai",
    "PSC pole Coimbatore",
    "RCC pole Coimbatore",
    "electric pole supplier Coimbatore",
    "PSC pole Madurai",
    "RCC pole Madurai",
    "electric pole manufacturer Madurai",
    "PSC pole Trichy",
    "RCC pole Trichy",
    "PSC pole Tiruchirappalli",
    "electric pole supplier Trichy",
    "PSC pole Salem",
    "RCC pole Salem",
    "PSC pole Tirunelveli",
    "RCC pole Tirunelveli",
    "electric pole Kanyakumari",
    "PSC pole Vellore",
    "RCC pole Vellore",
    "electric pole Tirupur",
    "PSC pole south India",
    "RCC pole south India",
    "electric pole manufacturer south India",
    "PSC pole Pudukkottai",
    "RCC pole Pudukkottai",
    "electric pole Pudukkottai district",
    // Application keywords
    "street lighting poles",
    "street light pole manufacturer",
    "street lighting pole tamil nadu",
    "HT line poles",
    "LT line poles",
    "high tension poles",
    "low tension poles",
    "power distribution poles",
    "rural electrification poles",
    "rural electrification pole manufacturer",
    "transmission poles tamil nadu",
    "distribution line poles",
    // Indian Standards
    "IS 1678 poles",
    "IS 2905 PSC poles",
    "IS 7321 electric poles",
    "ISI standard poles",
    "BIS certified poles",
    // Buyer intent keywords
    "electric pole near me",
    "PSC pole near me",
    "RCC pole near me",
    "PSC pole price list",
    "RCC pole price list tamil nadu",
    "electric pole wholesale",
    "bulk electric poles",
    "RCC pole wholesale supplier",
    "PSC pole wholesale tamilnadu",
    "electric pole dealer",
    "electric pole dealer tamil nadu",
    "concrete pole cost",
    "electric pole quotation",
    "TNEB approved pole manufacturer",
    "TNEB approved PSC pole supplier",
    "TNEB approved RCC pole manufacturer",
    // Base plate keywords
    "pole base plate",
    "pole base plate manufacturer",
    "pole base plate tamil nadu",
    "pole foundation plate",
    "concrete base plate for pole",
    "electric pole foundation",
    "electric pole base plate supplier",
    "anchor plate for electric pole",
    "RCC base plate price",
    "base plate for PSC pole",
    "base plate for RCC pole",
    // TN abbreviation variants
    "buy psc pole TN",
    "buy psc poles TN",
    "buy rcc pole TN",
    "buy rcc poles TN",
    "buy electric pole TN",
    "psc pole manufacturers TN",
    "rcc pole manufacturers TN",
    "electric pole suppliers TN",
    "psc pole price TN",
    "rcc pole price TN",
    "TNEB pole manufacturers TN",
    "buy base plate TN",
    // TANGEDCO keywords (current name of TNEB)
    "TANGEDCO pole suppliers",
    "TANGEDCO pole manufacturers",
    "TANGEDCO approved pole manufacturer",
    "TANGEDCO approved PSC pole",
    "TANGEDCO approved RCC pole",
    "TANGEDCO pole suppliers tamilnadu",
    "TANGEDCO pole price",
    "TANGEDCO standard electric pole",
    // Local Tamil terms (high local intent)
    "current kambam",
    "minsara kambam",
    "current pole tamilnadu",
    "current pole manufacturer",
    "EB pole tamilnadu",
    "EB pole manufacturers tamil nadu",
    "EB pole supplier",
    "buy EB pole tamilnadu",
    "EB pole price",
    // Government scheme keywords
    "DDUGJY poles supplier tamilnadu",
    "Saubhagya scheme poles",
    "rural electrification scheme poles",
    "RGGVY poles supplier tamil nadu",
    "PM KUSUM scheme poles",
    "government tender electric poles tamilnadu",
    "TNEB tender pole supplier",
    "TANGEDCO tender pole manufacturer",
    // Nearby district keywords
    "PSC pole Thanjavur",
    "RCC pole Thanjavur",
    "electric pole Thanjavur",
    "PSC pole Sivagangai",
    "RCC pole Sivagangai",
    "PSC pole Dindigul",
    "RCC pole Dindigul",
    "PSC pole Karur",
    "RCC pole Karur",
    "PSC pole Ramanathapuram",
    "RCC pole Ramanathapuram",
    "PSC pole Nagapattinam",
    "RCC pole Nagapattinam",
    "PSC pole Ariyalur",
    "RCC pole Ariyalur",
    "PSC pole Perambalur",
    "electric pole Erode",
    "PSC pole Theni",
    "electric pole Thoothukudi",
    "RCC pole Virudhunagar",
    "PSC pole Cuddalore",
    "RCC pole Villupuram",
    "PSC pole Kanchipuram",
    "electric pole Tiruvannamalai",
    // Neighbouring state keywords
    "PSC pole Kerala",
    "RCC pole Kerala",
    "electric pole supplier Kerala",
    "PSC pole Karnataka",
    "RCC pole Karnataka",
    "buy PSC pole Pondicherry",
    "RCC pole Puducherry",
    "electric pole supplier Andhra Pradesh",
    // Comparison & informational keywords
    "PSC pole vs RCC pole",
    "difference between PSC and RCC pole",
    "which is better PSC or RCC pole",
    "concrete pole vs steel pole",
    "wooden pole vs concrete pole",
    "PSC pole advantages",
    "RCC pole advantages",
    "PSC pole lifespan",
    "RCC pole lifespan",
    "electric pole weight",
    "electric pole specifications",
    // Cost & budget keywords
    "cheapest electric pole tamilnadu",
    "affordable PSC pole tamil nadu",
    "low cost RCC pole tamilnadu",
    "electric pole cost per unit",
    "PSC pole price per piece",
    "RCC pole rate per piece",
    "electric pole price list 2026",
    "PSC pole price list 2026",
    "RCC pole rate list tamilnadu",
    "electric pole quotation online",
    "bulk pole price tamilnadu",
    "wholesale electric pole price",
    // Application-specific keywords
    "CCTV pole manufacturer tamilnadu",
    "highway lighting pole manufacturer",
    "overhead line poles",
    "11kv line poles",
    "33kv line poles",
    "440v line poles",
    "transformer pole tamilnadu",
    "electricity distribution pole",
    // Long-tail question keywords
    "how much does an electric pole cost in tamil nadu",
    "how to buy electric pole in tamilnadu",
    "who manufactures electric poles in tamil nadu",
    "electric pole manufacturer near pudukkottai",
    "where to buy concrete pole near me",
    "best electric pole company in tamilnadu",
    "how to order poles for TNEB project",
    "what is the price of 9m PSC pole",
    "what is the weight of RCC pole",
    // Common misspellings & alternate terms
    "buy PCC pole tamilnadu",
    "buy PCC poles tamil nadu",
    "cement pole tamilnadu",
    "buy cement pole tamil nadu",
    "cement pole manufacturer",
    "buy cement pole",
  ],
  authors: [{ name: "Gemini Engineering Works" }],
  creator: "Gemini Engineering Works",
  publisher: "Gemini Engineering Works",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: "website",
    locale: "en_IN",
    url: "https://geminiengineeringworks.in/",
    siteName: "Gemini Engineering Works",
    title: "Buy PSC & RCC Poles in Tamil Nadu | Gemini Engineering Works",
    description:
      "Buy PSC poles and RCC poles in Tamil Nadu from Gemini Engineering Works. Leading manufacturer since 1999 in Pudukkottai, Tamilnadu. TNEB approved. Bulk orders welcome.",
    images: [
      {
        url: "/logo.webp",
        width: 1200,
        height: 630,
        alt: "Gemini Engineering Works - PSC & RCC Electric Pole Manufacturers",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Buy PSC & RCC Poles in Tamil Nadu | Gemini Engineering Works",
    description:
      "Buy PSC poles and RCC poles in Tamil Nadu. Leading manufacturer since 1999 in Pudukkottai, Tamilnadu. TNEB approved.",
    images: ["/logo.webp"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {
    // Add your verification codes when available
    // google: "your-google-verification-code",
    // yandex: "your-yandex-verification-code",
    // bing: "your-bing-verification-code",
  },
  alternates: {
    canonical: "https://geminiengineeringworks.in/", // Update with your actual domain
  },
  category: "Manufacturing",
  icons: {
    icon: "/icon.ico",
    apple: "/icon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <body>
        {children}
        <WhatsAppButton />
      </body>
    </html>
  );
}
